# Colors (Challenger Deep)

# Default colors
[colors.primary]
background = '#1e1c31'
foreground = '#cbe1e7'

[colors.cursor]
text = '#ff271d'
cursor = '#fbfcfc'

# Normal colors
[colors.normal]
black = '#141228'
red = '#ff5458'
green = '#62d196'
yellow = '#ffb378'
blue = '#65b2ff'
magenta = '#906cff'
cyan = '#39c5cf'
white = '#a6b3cc'

# Bright colors
[colors.bright]
black = '#565575'
red = '#ff8080'
green = '#4ae168'
yellow = '#f7c843'
blue = '#91cbff'
magenta = '#cb9eff'
cyan = '#39c5cf'
white = '#d9dee3'

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["-l", "-c", "zellij"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
